### ISSUE TITLE
modelarts 训练作业时提示缺少某个 python 库

### ISSUE THREAD

**Issue by snowhou** [DataFountainCode/huawei_code_share#3]
当在 east 训练阶段时，运行 multigpu_train.py 时提示，
`ModuleNotFoundError: No module named 'shapely'`
我看到作者已经在 icdar 文件中增加了
`import os`
`os.system('pip install shapely')`
但我运行时会报如下错误
`Could not find a version that satisfies the requirement shapely (from versions: ) No matching distribution found for shapely Collecting shapely The repository located at http is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host http'`

我尝试改为
`import os`
`os.system('pip install shapely --trusted-host http')`
出现如下错误
`('<pip._vendor.requests.packages.urllib3.connection.HTTPConnection object at 0x7fb67de73cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': //repo.myhuaweicloud.com/repository/pypi/simple/shapely/ Could not find a version that satisfies the requirement shapely (from versions: ) No matching distribution found for shapely Collecting shapely The repository located at http is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host http'. Could not find a version that satisfies the requirement shapely (from versions: )`
我在 multigpu_train.py 中也尝试了上面的修改，还是同样的错误
作者当时是否遇到了这样的问题，应该怎么解决呢？

**Comment by MIUXIU** [comment]
修改为
os.system('pip install http://mirrors.myhuaweicloud.com/pypi/web/packages/38/b6'
          '/b53f19062afd49bb5abd049aeed36f13bf8d57ef8f3fa07a5203531a0252/Shapely-1.6.4.post2-cp36-cp36m'
          '-manylinux1_x86_64.whl')
亲测可行

**Comment by snowhou** [comment]
> 修改为
> os.system('pip install http://mirrors.myhuaweicloud.com/pypi/web/packages/38/b6'
> '/b53f19062afd49bb5abd049aeed36f13bf8d57ef8f3fa07a5203531a0252/Shapely-1.6.4.post2-cp36-cp36m'
> '-manylinux1_x86_64.whl')
> 亲测可行

  @MIUXIU 哈哈哈，终于成功了，太感谢了
具体如下：
在 multigpu_train.py 添加
`import os`
`os.system('pip install http://mirrors.myhuaweicloud.com/pypi/web/packages/38/b6/b53f19062afd49bb5abd049aeed36f13bf8d57ef8f3fa07a5203531a0252/Shapely-1.6.4.post2-cp36-cp36m-manylinux1_x86_64.whl')`
在 icdar.py 注释掉
`os.system('pip install shapely')`

**Comment by YTALIEN** [comment]
你好，请问如果要安装别的库那个地址应该如何找呢？

**Comment by YTALIEN** [comment]
> 修改为 os.system('pip install http://mirrors.myhuaweicloud.com/pypi/web/packages/38/b6' '/b53f19062afd49bb5abd049aeed36f13bf8d57ef8f3fa07a5203531a0252/Shapely-1.6.4.post2-cp36-cp36m' '-manylinux1_x86_64.whl') 亲测可行

请问如何找到这个对应网址呀，比如我要安装distance库，但是无法找到直接是whl文件的地址
